version: '3.1'

services:

  maria:
    build:
      context: .
      dockerfile: Dockerfile # Verweist auf dein Dockerfile
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "schueler" # Kein Passwort für den Root-Benutzer
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./SQL_Dumps:/var/lib/mysql-dumps # Mappe den lokalen SQL_Dumps Ordner in den Container

  phpmyadmin:
    depends_on:
      - maria
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: maria
      MYSQL_ROOT_PASSWORD: "schueler" # Kein Passwort für den Root-Benutzer

  webserver:
    depends_on:
    - maria
    image: httpd:latest
    ports:
      - "80:80"
    volumes:
      - ./htdocs:/usr/local/apache2/htdocs
    environment:
      PMA_HOST: maria
      MYSQL_ROOT_PASSWORD: "schueler" # Kein Passwort für den Root-Benutzer

volumes:
  db_data:
  htdocs:



